name: 1002 Sync
on:
  workflow_dispatch:  # 手动触发

jobs:
  1002-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run 1002 sync
        run: npm run 1002
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          D1_DATABASE_ID: ${{ secrets.D1_DATABASE_ID }}
          SYNC_PAGE_LIMIT: ${{ vars.SYNC_PAGE_LIMIT || '1' }}
          SYNC_DELAY_MS: ${{ vars.SYNC_DELAY_MS || '2000' }}
