name: Sync Migu Data
on:
  schedule:
    - cron: '0 1 * * *'  # 每天凌晨1点增量同步
  workflow_dispatch:      # 手动触发
    inputs:
      action:
        description: '执行的操作'
        required: true
        default: 'incremental'
        type: choice
        options:
        - incremental

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run incremental sync
        run: node src/incremental-sync.js
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          D1_DATABASE_ID: ${{ secrets.D1_DATABASE_ID }}
