# .github/workflows/update-sports-data.yml
name: Update Sports Data

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-sports-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Generate sports data
        run: node scripts/generate-sports-data.js

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/sports-data.json
          git diff --staged --quiet || git commit -m "Auto-update sports data [$(date +'%Y-%m-%d %H:%M')]"
          git push
